= Update the ejb3 Subsystem

The JBoss Server Migration Tool makes the following updates to the *ejb3* subsystem configuration to better match the {server-target-productName} default configurations.

* The remote service configuration is updated to reference the new HTTP connector.
* The `default-sfsb-passivation-disabled-cache` attribute is configured to use the `efault-sfsb-cache`.
* Legacy passivation store and cache configurations are replaced with the {server-target-productName} defaults.

By default, the tool updates any *ejb3* subsystem configuration to include these changes.
If you prefer, you can configure the environment properties to customize the process of updating the *ejb3* subsystem configuration.

|===
| Property Name |Property Description

| `subsystem.ejb3.update.skip` | If set to `true`, the tool skips the update of the *ejb3* subsystem.
| `subsystem.ejb3.update.activate-ejb3-remoting-http-connector.skip` | If set to `true`, the tool does not update the `EJB Remoting` configuration.
| `subsystem.ejb3.update.add-infinispan-passivation-store-and-distributable-cache.skip` | If set to `true`, the tool does not replace the `passivation store` and `cache` configurations.
| `subsystem.ejb3.update.setup-default-sfsb-passivation-disabled-cache.skip` | If set to `true`, the tool does not update the `default-sfsb-passivation-disabled-cache` configuration.
|===

Upon successful migration of the *ejb3* subsystem configuration, you should see the following message in the console:
[source,options="nowrap"]
----
 INFO  Subsystem ejb3 updated.
----
