= Update the ee Subsystem

The *ee* Subsystem in {server-target-productName} provides support for Jakarta EE features.

* You can configure instances of Jakarta EE concurrency utilities, such as container-managed `Executors`.
* You can define the Jakarta EE default resources, such as the default data source, by specifying the original JNDI addresses.

By default, the tool updates the *ee* subsystem configuration to include the new features, printing the following message in the console/logs:
[source,options="nowrap"]
----
 INFO  Subsystem ee updated.
----

If you prefer, you can configure the environment properties to customize the process of updating the *ee* subsystem configuration.

|===
| Property Name |Property Description

| `subsystem.ee.update.skip` | If set to `true`, the tool skips the update of the *ee* subsystem.
| `subsystem.ee.update.setup-ee-concurrency-utilities.skip` | If set to `true`, the tool does not add the default instances of concurrency utilities
| `subsystem.ee.update.setup-jakartaee-default-bindings.skip` | If set to `true`, the tool does not set up Jakarta EE default resources.
| `subsystem.ee.update.setup-jakartaee-default-bindings.defaultDataSourceName` | Specifies the name of the default data source to look for in the source configuration.
| `subsystem.ee.update.setup-jakartaee-default-bindings.defaultDataSourceJndiName` | Specifies the JNDI name for the default data source.
| `subsystem.ee.update.setup-jakartaee-default-bindings.defaultJmsConnectionFactoryName` | Specifies the name of the JMS connection factory.
| `subsystem.ee.update.setup-jakartaee-default-bindings.defaultJmsConnectionFactoryJndiName` | Specifies the JNDI name for the default JMS connection factory.
|===

WARNING: JNDI names that are specified are assumed to be valid. JNDI names are not validated by the tool.

For concurrency utilities instances, the tool automatically configures the exact same instances that are present in all {server-target-productName} default configurations and does not require any user interaction.

When defining Jakarta EE default resources, by default the tool looks for the resources present in default {server-source-productName} configurations and select these if present.
In the case where the tool does not find such resources, then user input is required.
The tool lists all available resources in the configuration, and then asks the user to select the one that should be set as the default, or to manually provide the JNDI address of the original resource.
The following is an example of the interaction that occurs when migrating a configuration file with two configured data sources, `ExampleDS1` and `ExampleDS2` and defining the default data source:

[source,options="nowrap"]
----
INFO  Default datasource not found.
0. ExampleDS
1. Unconfigured data source, I want to enter the JNDI name...
Please select Jakarta EE's Default Datasource: (0): 0

Save this Jakarta EE Default Datasource JNDI name and use it when migrating other config files?
yes/no? y
----

NOTE: If you run the migration tool in `non-interactive` mode and the expected {server-source-productName} default resources are not available, for example the default JMS connection factory, the tool will not configure those resources.
