= Update the infinispan Subsystem

The JBoss Server Migration Tool makes the following updates to the *infinispan* subsystem configuration to better match the {server-target-productName} default configurations.

* Adds the `server` cache, which is present in the {server-target-productName} default configuration.
* Fixes the module name in the `hibernate` cache configuration.
* Adds `concurrent` cache to the `web` cache container, which is present in the {server-target-productName} default configuration.

By default, the tool automatically updates any *infinispan* subsystem configuration to include these changes.
If you prefer, you can configure the environment properties to customize the process of updating the *infinispan* subsystem configuration.

|===
| Property Name |Property Description

| `subsystem.infinispan.update.skip` | If set to `true`, the tool skips the update of the *infinispan* subsystem.
| `subsystem.infinispan.update.add-infinispan-server-cache.skip` | If set to `true`, the tool does not add the `server` cache.
| `subsystem.infinispan.update.fix-hibernate-cache-module-name.skip` | If set to `true`, the tool does not fix the module name in the `hibernate` cache configuration.
| `subsystem.infinispan.update.update-infinispan-web-cache.skip` | If set to `true`, the tool does not adds `concurrent` cache to the `web` cache container.
|===

Upon successful migration of a *infinispan* subsystem configuration, you should see the following message in the console:

[source,options="nowrap"]
----
 INFO  Subsystem infinispan updated.
----
