= Update the undertow Subsystem

The JBoss Server Migration Tool applies the following changes to *undertow* subsystem configurations.

* Sets the default `Server` response header.
* Sets the default `X-Powered-By` response header.
* Sets the default `HTTP Invoker`.

By default, the tool automatically updates any *undertow* subsystem configuration to include these changes.
If you prefer, you can configure the environment properties to customize the process of updating the *undertow* subsystem configuration.

|===
| Property Name |Property Description

| `subsystem.undertow.update.skip` | If set to `true`, the tool skips the update of the *undertow* subsystem.
| `subsystem.undertow.update.add-response-header.server-header.skip` | If set to `true`, the tool does not set the default `Server` response header.
| `subsystem.undertow.update.add-response-header.x-powered-by-header.skip` | If set to `true`, the tool does not set the default `X-Powered-By` response header.
| `subsystem.undertow.update.add-http-invoker.skip` | If set to `true`, the tool does not sets the default `HTTP Invoker`.
|===

Upon successful migration of a *undertow* subsystem configuration, you should see messages in the console such as:

[source,options="nowrap"]
----
INFO  [ServerMigrationTask#37] Response header 'server-header' set as 'Server: WildFly/11' in Undertow's config /subsystem=undertow
INFO  [ServerMigrationTask#38] Response header 'x-powered-by-header' set as 'X-Powered-By: Undertow/1' in Undertow's config /subsystem=undertow
INFO  [ServerMigrationTask#39] Undertow's default host http-invoker configured.
----
