= Update the undertow Subsystem

The JBoss Server Migration Tool applies the following changes to *undertow* subsystem configurations.

* Sets the default `HTTP Listener` redirect socket.
* Sets the default `Server` response header.

By default, the tool automatically updates any *undertow* subsystem configuration to include these changes.
If you prefer, you can configure the environment properties to customize the process of updating the *undertow* subsystem configuration.

|===
| Property Name |Property Description

| `subsystem.undertow.update.skip` | If set to `true`, the tool skips the update of the *undertow* subsystem.
| `subsystem.undertow.update.set-default-http-listener-redirect-socket.skip` | If set to `true`, the tool does not set the default `HTTP Listener` redirect socket.
| `subsystem.undertow.update.add-response-header.server-header.skip` | If set to `true`, the tool does not set the default `Server` response header.
|===

Upon successful migration of a *undertow* subsystem configuration, you should see the following message in the console:

[source,options="nowrap"]
----
 INFO  Subsystem undertow updated.
----
