= Migrate {subsystem-migrate-legacySubsystemName} Subsystem

The *{subsystem-migrate-legacySubsystemName}* subsystem is deprecated in {server-target-productName} and is replaced by the *{subsystem-migrate-replacementSubsystemName}* subsystem.

By default, the JBoss Server Migration Tool automatically migrates any legacy subsystem configuration found.
If you prefer this migration task is not executed, you can set the `subsystem.{subsystem-migrate-legacySubsystemName}.migrate.skip` environment property value to `true`.

The legacy subsystem migration is done without requiring any interaction from the user.

The outcome of the legacy *{subsystem-migrate-legacySubsystemName}* subsystem migration is printed in the console, as an example:

// sets value of console's "subsystem config migrated" line depending if config is domain or standalone
ifeval::["{server-migration-serverConfigurationType}" == "Domain"]
:subsystem-migrate-console-body: INFO  [ServerMigrationTask#335] (main) Subsystem config /profile=default/subsystem={subsystem-migrate-legacySubsystemName} migrated.
endif::[]

ifeval::["{server-migration-serverConfigurationType}" == "Standalone"]
:subsystem-migrate-console-body:  INFO  [ServerMigrationTask#335] (main) Subsystem config /subsystem={subsystem-migrate-legacySubsystemName} migrated.
endif::[]

[source,options="nowrap",subs="attributes"]
----
INFO  [ServerMigrationTask#331] (main) Migrating subsystem {subsystem-migrate-legacySubsystemName} configurations...
{subsystem-migrate-console-body}
INFO  [ServerMigrationTask#336] (main) Extension {subsystem-migrate-legacyExtensionName} removed.
INFO  [ServerMigrationTask#331] (main) Subsystem {subsystem-migrate-legacySubsystemName} configurations migrated.
----

Any issues encountered during the migration are written to the log files and displayed in the migration console.