= Update the messaging-activemq Subsystem

In addition to migrating the *messaging* subsystem to {server-target-productName}, the JBoss Server Migration Tool also adds the following new functionality provided by the *messaging-activemq* subsystems, which is configured in the {server-target-productName} default standalone configuration files.

* Adds the default HTTP connector and acceptor, enabling the new HTTP-based remote messaging clients.

By default, the tool automatically updates any *messaging-activemq* subsystem configuration.
If you prefer, you can set the `subsystem.messaging-activemq.update.skip` environment property to `true` to skip automatic update of *messaging-activemq* subsystem configurations.

Upon successful migration of a *messaging-activemq* subsystem configuration, you should see the following messages in the console:

[source,options="nowrap"]
----
INFO  [ServerMigrationTask#123] HTTP Acceptor named http-acceptor added to Messaging ActiveMQ subsystem configuration.
INFO  [ServerMigrationTask#123] HTTP Connector named http-connector added to Messaging ActiveMQ subsystem configuration.
----